# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(700, 400)
        self.horizontalLayout = QtWidgets.QHBoxLayout(Dialog)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.icon_widget = QtWidgets.QWidget(Dialog)
        self.icon_widget.setStyleSheet("QWidget {\n"
"background-color: qlineargradient(spread:pad, x1:0.0852273, y1:1, x2:1, y2:0, stop:0 rgb(41, 143, 204), stop:1 rgb(47, 178, 236));\n"
"\n"
"}\n"
"")
        self.icon_widget.setObjectName("icon_widget")
        self.icon = QtWidgets.QLabel(self.icon_widget)
        self.icon.setGeometry(QtCore.QRect(70, 100, 200, 200))
        self.icon.setStyleSheet("background-color:transparent;")
        self.icon.setPixmap(QtGui.QPixmap("./resources/icons/user.png"))
        self.icon.setScaledContents(True)
        self.icon.setAlignment(QtCore.Qt.AlignCenter)
        self.icon.setObjectName("icon")
        self.horizontalLayout.addWidget(self.icon_widget)
        self.login_widget = QtWidgets.QWidget(Dialog)
        self.login_widget.setStyleSheet("QWidget{\n"
"background-color: rgb(255, 255, 255);\n"
"border-top:1px solid rgb(202, 202, 202);\n"
"}\n"
"QLineEdit{\n"
"border: 2px solid rgb(202, 202, 202);\n"
"border-radius: 5px;\n"
"}\n"
"")
        self.login_widget.setObjectName("login_widget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.login_widget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(30, 80, 291, 241))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.User_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.User_label.setFont(font)
        self.User_label.setStyleSheet("border-top:0px solid ;")
        self.User_label.setObjectName("User_label")
        self.verticalLayout.addWidget(self.User_label)
        self.User = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.User.setMinimumSize(QtCore.QSize(0, 30))
        self.User.setStyleSheet("")
        self.User.setObjectName("User")
        self.verticalLayout.addWidget(self.User)
        spacerItem = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.Password_label = QtWidgets.QLabel(self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.Password_label.setFont(font)
        self.Password_label.setStyleSheet("border-top:0px solid ;")
        self.Password_label.setObjectName("Password_label")
        self.verticalLayout.addWidget(self.Password_label)
        self.Password = QtWidgets.QLineEdit(self.verticalLayoutWidget)
        self.Password.setMinimumSize(QtCore.QSize(0, 30))
        self.Password.setStyleSheet("")
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.verticalLayout.addWidget(self.Password)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem1)
        self.login_btn = QtWidgets.QPushButton(self.verticalLayoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.login_btn.sizePolicy().hasHeightForWidth())
        self.login_btn.setSizePolicy(sizePolicy)
        self.login_btn.setMinimumSize(QtCore.QSize(100, 30))
        self.login_btn.setMaximumSize(QtCore.QSize(100, 30))
        font = QtGui.QFont()
        font.setFamily("MS Shell Dlg 2")
        font.setPointSize(12)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        font.setKerning(True)
        self.login_btn.setFont(font)
        self.login_btn.setStyleSheet("background-color: rgb(41, 143, 204);\n"
"color: rgb(255, 255, 255);\n"
"border:0px solid;\n"
"")
        self.login_btn.setObjectName("login_btn")
        self.verticalLayout.addWidget(self.login_btn)
        self.horizontalLayout.addWidget(self.login_widget)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.User_label.setText(_translate("Dialog", "Логин"))
        self.Password_label.setText(_translate("Dialog", "Пароль"))
        self.login_btn.setText(_translate("Dialog", "Войти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
