# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'loginDialog.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(450, 550)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(40, 30, 370, 480))
        self.widget.setStyleSheet("QWidget{\n"
"background:transparent;\n"
"}\n"
"QPushButton#login_btn{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.511, stop:0 rgba(91, 114, 122, 160), stop:0.369318 rgba(111, 145, 197, 110));\n"
"color: rgba(255, 255, 255, 210);\n"
"border-radius: 5px;\n"
"}\n"
"QPushButton#login_btn:hover{\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0.5, x2:1, y2:0.511, stop:0 rgba(111, 134, 142, 160), stop:0.369318 rgba(131, 165, 217, 130));\n"
"}\n"
"QPushButton#login_btn:pressed{\n"
"padding-left:5px;\n"
"padding-top:5px;\n"
"background-color:rgba(131, 165, 217, 100)\n"
"}\n"
"QPushButton#close_btn{\n"
"background-image: url(:/images/close_black.png);\n"
"border-radius: 5px;\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"}\n"
"QPushButton#close_btn:hover{\n"
"background-image: url(:/images/close_white.png);\n"
"background-color: rgba(0, 0, 0, 100);\n"
"}\n"
"QPushButton#collapse_btn{\n"
"background-image: url(:/images/minus_black.png);\n"
"border-radius: 5px;\n"
"background-repeat: no-repeat;\n"
"background-position: center;\n"
"}\n"
"QPushButton#collapse_btn:hover{\n"
"background-image: url(:/images/minus_white.png);\n"
"background-color: rgba(0, 0, 0, 100);\n"
"}")
        self.widget.setObjectName("widget")
        self.header_1 = QtWidgets.QLabel(self.widget)
        self.header_1.setGeometry(QtCore.QRect(40, 30, 300, 400))
        self.header_1.setMinimumSize(QtCore.QSize(300, 400))
        self.header_1.setStyleSheet("border-image: url(:/images/background2.jpg);\n"
"border-radius:20px;")
        self.header_1.setText("")
        self.header_1.setObjectName("header_1")
        self.header_2 = QtWidgets.QLabel(self.widget)
        self.header_2.setGeometry(QtCore.QRect(40, 30, 300, 400))
        self.header_2.setMinimumSize(QtCore.QSize(300, 400))
        self.header_2.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0.505, y1:0.0910909, x2:0.505455, y2:1, stop:0 rgba(172, 215, 230, 160), stop:0.369318 rgba(111, 145, 197, 110));\n"
"border-radius:20px;")
        self.header_2.setText("")
        self.header_2.setObjectName("header_2")
        self.backgrond = QtWidgets.QLabel(self.widget)
        self.backgrond.setGeometry(QtCore.QRect(50, 60, 280, 370))
        self.backgrond.setMinimumSize(QtCore.QSize(0, 370))
        self.backgrond.setStyleSheet("background-color: rgba(0, 0, 0, 100);\n"
"border-radius:15px;")
        self.backgrond.setText("")
        self.backgrond.setObjectName("backgrond")
        self.login = QtWidgets.QLabel(self.widget)
        self.login.setGeometry(QtCore.QRect(100, 90, 180, 40))
        font = QtGui.QFont()
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.login.setFont(font)
        self.login.setStyleSheet("color: rgba(255, 255, 255, 210);")
        self.login.setObjectName("login")
        self.User = QtWidgets.QLineEdit(self.widget)
        self.User.setGeometry(QtCore.QRect(90, 170, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.User.setFont(font)
        self.User.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
"color: rgba(255, 255, 255, 230);\n"
"padding-bottom: 7px;")
        self.User.setObjectName("User")
        self.Password = QtWidgets.QLineEdit(self.widget)
        self.Password.setGeometry(QtCore.QRect(90, 230, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.Password.setFont(font)
        self.Password.setStyleSheet("background-color: rgba(0, 0, 0, 0);\n"
"border: none;\n"
"border-bottom: 2px solid rgba(105, 118, 132, 255);\n"
"color: rgba(255, 255, 255, 230);\n"
"padding-bottom: 7px;")
        self.Password.setEchoMode(QtWidgets.QLineEdit.Password)
        self.Password.setObjectName("Password")
        self.login_btn = QtWidgets.QPushButton(self.widget)
        self.login_btn.setGeometry(QtCore.QRect(90, 322, 200, 40))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.login_btn.setFont(font)
        self.login_btn.setObjectName("login_btn")
        self.close_btn = QtWidgets.QPushButton(self.widget)
        self.close_btn.setGeometry(QtCore.QRect(300, 40, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.close_btn.setFont(font)
        self.close_btn.setText("")
        self.close_btn.setObjectName("close_btn")
        self.collapse_btn = QtWidgets.QPushButton(self.widget)
        self.collapse_btn.setGeometry(QtCore.QRect(270, 40, 16, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setWeight(75)
        self.collapse_btn.setFont(font)
        self.collapse_btn.setText("")
        self.collapse_btn.setObjectName("collapse_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.login.setText(_translate("Dialog", "Авторизация"))
        self.User.setPlaceholderText(_translate("Dialog", "Имя пользователя"))
        self.Password.setPlaceholderText(_translate("Dialog", "Пароль"))
        self.login_btn.setText(_translate("Dialog", "Войти"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
